#!/bin/bash
# shellcheck disable=SC1091
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#

source "/boot/config/plugins/sesmon-ext/sesmon-ext.cfg"

echo "Writing configuration..."
echo "Writing configuration..." | logger -t "sesmon-ext"

mkdir -p /boot/config/plugins/sesmon-ext/config
cp -rf /etc/sesmon-ext/* /boot/config/plugins/sesmon-ext/config/
